"use client"

import { useState } from "react"
import { saveAnnouncement, saveEditor, saveResults, saveTournament } from "@/app/actions/uec-management"

type Tournament = { id: string; number: number; name: string; status: string; published: boolean }
type Editor = { id: string; name: string; username: string }

export function UecManagementWorkspace({ initialTournaments, initialEditors }: { initialTournaments: Tournament[]; initialEditors: Editor[] }) {
  const [section, setSection] = useState("overview")
  const [message, setMessage] = useState("")
  const [pending, setPending] = useState(false)
  async function run(action: () => Promise<void>) { setPending(true); setMessage(""); try { await action(); setMessage("Saved successfully.") } catch { setMessage("Could not save this change. Check the fields and try again.") } finally { setPending(false) } }
  return <div className="uec-management"><aside className="management-nav"><p className="eyebrow">UEC ADMIN</p>{["overview", "tournaments", "results", "announcements", "editors"].map((item) => <button className={section === item ? "active" : ""} onClick={() => setSection(item)} key={item}>{item}</button>)}</aside><section className="management-content"><div className="management-header"><div><p className="eyebrow">CONTROL CENTER</p><h1>{section === "overview" ? "UEC Management" : section}</h1></div><span className="management-status">{pending ? "Saving…" : message || "All systems ready"}</span></div>{section === "overview" && <div className="management-cards"><div><span>Tournaments</span><strong>{initialTournaments.length}</strong></div><div><span>Editors</span><strong>{initialEditors.length}</strong></div><div><span>Publishing</span><strong>Ready</strong></div><div><span>Archive</span><strong>Protected</strong></div></div>}{section === "tournaments" && <TournamentForm pending={pending} run={run} />}{section === "editors" && <EditorForm pending={pending} run={run} />}{section === "announcements" && <AnnouncementForm pending={pending} run={run} tournaments={initialTournaments} />}{section === "results" && <ResultsForm pending={pending} run={run} tournaments={initialTournaments} editors={initialEditors} />}{section === "overview" && <div className="management-empty"><p className="eyebrow">NEXT RELEASE</p><h2>Create Tournament 4 without touching code.</h2><p>Use the sections on the left to create a tournament, publish an announcement, add editor profiles, and prepare Top 10 results.</p></div>}</section></div>
}

function TournamentForm({ run, pending }: { run: (action: () => Promise<void>) => void; pending: boolean }) { const [form, setForm] = useState({ number: 4, name: "UEC Tournament 4", status: "UPCOMING", description: "", startAt: "", deadlineAt: "", rules: "" }); return <FormCard title="Create tournament" onSubmit={(event) => { event.preventDefault(); void run(() => saveTournament({ ...form, rules: form.rules.split("\n").map((rule) => rule.trim()).filter(Boolean), published: true })) }} pending={pending}><Field label="Tournament number"><input type="number" value={form.number} onChange={(event) => setForm({ ...form, number: Number(event.target.value) })} /></Field><Field label="Name"><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Field><Field label="Status"><select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option>UPCOMING</option><option>LIVE</option><option>SUBMISSIONS OPEN</option><option>JUDGING</option><option>RESULTS SOON</option><option>COMPLETED</option></select></Field><Field label="Description"><textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></Field><Field label="Rules, one per line"><textarea value={form.rules} onChange={(event) => setForm({ ...form, rules: event.target.value })} /></Field><div className="form-grid"><Field label="Start"><input type="datetime-local" value={form.startAt} onChange={(event) => setForm({ ...form, startAt: event.target.value })} /></Field><Field label="Deadline"><input type="datetime-local" value={form.deadlineAt} onChange={(event) => setForm({ ...form, deadlineAt: event.target.value })} /></Field></div></FormCard> }
function EditorForm({ run, pending }: { run: (action: () => Promise<void>) => void; pending: boolean }) { const [form, setForm] = useState({ name: "", username: "", shortBio: "", fullBio: "", profileImage: "", youtubeUrl: "" }); return <FormCard title="Create editor profile" onSubmit={(event) => { event.preventDefault(); void run(() => saveEditor(form)) }} pending={pending}><Field label="Display name"><input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Field><Field label="Username"><input required value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} /></Field><Field label="Profile image URL"><input value={form.profileImage} onChange={(event) => setForm({ ...form, profileImage: event.target.value })} /></Field><Field label="Short bio"><input value={form.shortBio} onChange={(event) => setForm({ ...form, shortBio: event.target.value })} /></Field><Field label="Full bio"><textarea value={form.fullBio} onChange={(event) => setForm({ ...form, fullBio: event.target.value })} /></Field><Field label="YouTube URL"><input value={form.youtubeUrl} onChange={(event) => setForm({ ...form, youtubeUrl: event.target.value })} /></Field></FormCard> }
function AnnouncementForm({ run, pending, tournaments }: { run: (action: () => Promise<void>) => void; pending: boolean; tournaments: Tournament[] }) { const [form, setForm] = useState({ title: "", shortDescription: "", content: "", tournamentId: "", status: "DRAFT" }); return <FormCard title="Create announcement" onSubmit={(event) => { event.preventDefault(); void run(() => saveAnnouncement(form)) }} pending={pending}><Field label="Title"><input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></Field><Field label="Tournament"><select value={form.tournamentId} onChange={(event) => setForm({ ...form, tournamentId: event.target.value })}><option value="">General announcement</option>{tournaments.map((tournament) => <option value={tournament.id} key={tournament.id}>UEC #{tournament.number} · {tournament.name}</option>)}</select></Field><Field label="Short description"><input value={form.shortDescription} onChange={(event) => setForm({ ...form, shortDescription: event.target.value })} /></Field><Field label="Content"><textarea required value={form.content} onChange={(event) => setForm({ ...form, content: event.target.value })} /></Field><Field label="Publishing"><select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option>DRAFT</option><option>PUBLISHED</option></select></Field></FormCard> }
function ResultsForm({ run, pending, tournaments, editors }: { run: (action: () => Promise<void>) => void; pending: boolean; tournaments: Tournament[]; editors: Editor[] }) { const [tournamentId, setTournamentId] = useState(tournaments[0]?.id || ""); const [rows, setRows] = useState(Array.from({ length: 10 }, (_, index) => ({ position: index + 1, editorId: "", editorName: "", editUrl: "", prize: "" }))); return <FormCard title="Results manager · Top 10" onSubmit={(event) => { event.preventDefault(); void run(() => saveResults(tournamentId, rows.filter((row) => row.editorName.trim()))) }} pending={pending}><Field label="Tournament"><select value={tournamentId} onChange={(event) => setTournamentId(event.target.value)}>{tournaments.map((tournament) => <option value={tournament.id} key={tournament.id}>UEC #{tournament.number} · {tournament.name}</option>)}</select></Field><div className="results-editor">{rows.map((row, index) => <div className="result-row" key={row.position}><strong>#{row.position}</strong><select value={row.editorId} onChange={(event) => { const editor = editors.find((item) => item.id === event.target.value); const next = [...rows]; next[index] = { ...next[index], editorId: event.target.value, editorName: editor?.name || next[index].editorName }; setRows(next) }}><option value="">Select editor</option>{editors.map((editor) => <option value={editor.id} key={editor.id}>{editor.name}</option>)}</select><input placeholder="Editor name" value={row.editorName} onChange={(event) => { const next = [...rows]; next[index] = { ...next[index], editorName: event.target.value }; setRows(next) }} /><input placeholder="Edit link" value={row.editUrl} onChange={(event) => { const next = [...rows]; next[index] = { ...next[index], editUrl: event.target.value }; setRows(next) }} /><input placeholder="Prize / award" value={row.prize} onChange={(event) => { const next = [...rows]; next[index] = { ...next[index], prize: event.target.value }; setRows(next) }} /></div>)}</div></FormCard> }
function FormCard({ title, children, onSubmit, pending }: { title: string; children: React.ReactNode; onSubmit: (event: React.FormEvent<HTMLFormElement>) => void; pending: boolean }) { return <form className="management-form" onSubmit={onSubmit}><div className="form-title"><h2>{title}</h2><button type="submit" disabled={pending}>{pending ? "Saving…" : "Save draft"}</button></div>{children}</form> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="management-field"><span>{label}</span>{children}</label> }
